The NumPy module gives us a new data type, the array. This object holds an array of fixed size, and all values inside are of the same type. The arrays can also be multidimensional, which is how we will use them with images. There's a bit more to it than this, but it is enough to get us started.

In [20]:
from numpy import *                    #import numeric

a = array((1,2,3,4,5))                 #create an array
print(a)                                      #display the array

print(a[2])                                 #index into the array

print(a*2)                                    #new array with twiced values

[1 2 3 4 5]
3
[ 2  4  6  8 10]


In [16]:
print(len(a))                                 #get array size
print(a[2:])                                  #elements 2 and up

print(a[:-2])                                 #all except last 2

b = a[2:] + a[:-2]
print(b)                         #add first and last

b = array((1,2,3)) + array((3,4,5))          #add arrays of wrong sizes
print(b)

5
[10  4  5]
[ 1  3 10]
[11  7 15]
[4 6 8]


It is very important to know that the new arrays created from slicing the original all reference the same values. So changing the values in a slice also changes the original values. It is important how this is done.

In [21]:
print(a)
aa = a[1:3]                            #slice middle 2 elements -- creates alias
print(aa)                              #show the slice

a[1] = 333
aa[1] = 44                             #chance value in slice
print(a, aa)                           #show change in original

aaa = array(a)                         #create separate array object
print(aaa )                            #show copy

aaa[1:4] = 0                           #set middle values to 0
print(aaa )                            #show copy

print(a )                         

[1 2 3 4 5]
[2 3]
[  1 333  44   4   5] [333  44]
[  1 333  44   4   5]
[1 0 0 0 5]
[  1 333  44   4   5]


Now we will look at small arrays with two dimensions. Don't be too worried, getting started it is the same as having a two dimensional tuple (a tuple inside a tuple). Let's get started with two dimensional arrays.

In [22]:
row1 = (1,2,3)                         #create a tuple of vals
row2 = (3,4,5)                         #another tuple

print(row1,row2)                       #show as a 2D tuple

b = array((row1, row2))                #create a 2D array
print(b)                               #show the array
print(array([[1, 2, 3],[3, 4, 5]]))

print(array(((1,2),(3,4),(5,6))))          #show a new 2D array

(1, 2, 3) (3, 4, 5)
[[1 2 3]
 [3 4 5]]
[[1 2 3]
 [3 4 5]]
[[1 2]
 [3 4]
 [5 6]]


In [23]:
print(b )                                     #show our array from above

print(b[0,1])                                #index a single value

print(b[1,:])                                 #slice second row

print(b[1])                                   #slice second row (same as above)

print(b[:,2])                                 #slice last column

print(b[:,:2]) 

[[1 2 3]
 [3 4 5]]
2
[3 4 5]
[3 4 5]
[3 5]
[[1 2]
 [3 4]]
