In [7]:
from numpy import *                    #import numeric

a = array((1,2,3,4,5))                 #create an array
print(a)                                      #display the array

print(a[2])                                 #index into the array

print(a*2)                                    #new array with twiced values

[1 2 3 4 5]
3
[ 2  4  6  8 10]


In [9]:
print(len(a))                                 #get array size
print(a[2:])                                  #elements 2 and up

print(a[:-2])                                 #all except last 2

b = a[2:] + a[:-2]
print(b)                         #add first and last

b = array((1,2,3)) + array((3,4,5))          #add arrays of wrong sizes
print(b)

5
[3 4 5]
[1 2 3]
[4 6 8]
[4 6 8]
